### ISSUE TITLE
Implement GitHub Action for Flux OCI push

### ISSUE THREAD

**Issue by stefanprodan** [controlplaneio-fluxcd/distribution#167]
We should develop a new GitHub action for publishing Flux OCI Artifacts to container registries.

Instead of using a [script like in this example](https://github.com/controlplaneio-fluxcd/flux-operator/blob/main/.github/workflows/push-manifests.yml) we could simplify the workflow as:

```yaml
name: push-manifests
on:
  push:
    branch: ['main']

jobs:
  flux-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push signed manifests
        uses: controlplaneio-fluxcd/distribution/actions/push@main
        with:
          path: ./manifests
          repository: ghcr.io/${{ github.repository }}-manifests
          tags: |-
            ${{ github.sha }}
            latest
          annotations: |-
            org.opencontainers.image.description=my description
            org.opencontainers.image.documentation=https://example.com
```
