### ISSUE TITLE
GitHub Webhook for Ephemeral Environments for GitHub Pull Requests

### ISSUE THREAD

**Issue by kmadel** [controlplaneio-fluxcd/distribution#172]
Based on the instructions here: https://fluxcd.control-plane.io/operator/resourcesets/github-pull-requests/#github-webhook

I installed Flux2 with community Helm chart: https://fluxcd-community.github.io/helm-charts revision 2.15.0

Installed Flux Operator from ghcr.io/controlplaneio-fluxcd/charts revision 0.17.0

I create the following resource:

```
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: pr-github-receiver
  namespace: p-auth-core
spec:
  type: github
  secretRef:
    name: pr-github-receiver-token
  resources:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: preview-pull-requests
```

Results in the following invalid spec issue:

```
Receiver.notification.toolkit.fluxcd.io "pr-github-receiver" is invalid: spec.resources[0].kind: 
Unsupported value: "ResourceSetInputProvider": 
supported values: "Bucket", "GitRepository", "Kustomization", "HelmRelease", "HelmChart", "HelmRepository", "ImageRepository", "ImagePolicy", "ImageUpdateAutomation", "OCIRepository"
```
